steps:
  - name: probe-daemon
    image: docker.io/library/alpine:3
    commands:
      - echo "DOCKER_HOST=[$DOCKER_HOST]"
      - ls -la /var/run/docker.sock 2>&1 || echo "NO SOCKET"
    when:
      event: [manual]

  - name: probe-buildx
    image: docker.io/woodpeckerci/plugin-docker-buildx
    settings:
      repo: ghcr.io/mel-cell/fastunduh
      tags: probe
      username:
        from_secret: ghcr_user
      password:
        from_secret: ghcr_token
    when:
      event: [manual]
